[theme]
primaryColor = "#F39C12"
backgroundColor = "#1E1E1E"
secondaryBackgroundColor = "#2D2D2D"
textColor = "#FFFFFF"

[server]
headless = true
port = 8501
enableCORS = false

[browser]
gatherUsageStats = false
